### ISSUE TITLE
Issues refactoring code

### ISSUE THREAD

**Issue by gchan82** [LoveMeWithoutAll/book-blog#1]
Hi Young,
Thank you for sharing your FileUploader.vue on website: 'https://lovemewithoutall.github.io/it/vue-image-upload-to-firestorage/ '

I am trying to get it to work with my project. I refactored your code into mine, but having a difficult time understanding what is wrong. Can you help me? Here is my github repo: https://github.com/gchan82/feedme . Maybe you can respond back on my github repo. Thank you.

**Comment by LoveMeWithoutAll** [comment]
> Hi Young,
> Thank you for sharing your FileUploader.vue on website: 'https://lovemewithoutall.github.io/it/vue-image-upload-to-firestorage/ '
> 
> I am trying to get it to work with my project. I refactored your code into mine, but having a difficult time understanding what is wrong. Can you help me? Here is my github repo: https://github.com/gchan82/feedme . Maybe you can respond back on my github repo. Thank you.

Perhaps you should just use firestorages for image upload?
